### ISSUE TITLE
Improve product category design

### ISSUE THREAD

**Issue by rezwan2525** [KiranAminPanjwani/LeatherHoard#33]
In our collections section, the category image is not properly circular shaped, also each product category can be a bootstrap card to look nice. 
Can we please do that?

**Comment by kritiag20** [comment]
Hi @rezwan2525, I want to work on this issue please assign to me

**Comment by KiranAminPanjwani** [comment]
> In our collections section, the category image is not properly circular shaped, also each product category can be a bootstrap card to look nice. Can we please do that?

Actually, I don't want to change their shape. But yes, you can make their titles clickable. So that users can open a particular category by clicking on its name and can see more variety of product cards.

For example here, only one type of shoe is shown here. While there are many more colors and designs of shoes for men's formal collections.

![image](https://user-images.githubusercontent.com/90326051/193621690-17c5375b-f311-4bee-861c-93bee36a6d00.png)
